version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexus-admin-web
    restart: always
    user: "0:0" # Run as root for SQLite write access
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - ./prisma:/app/prisma
